/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lol.typefast.trie;

import java.util.List;

import lol.typefast.trie.tree.PrefixTreeBuilder;
import lol.typefast.trie.tree.Trie;

/**
 * Will need to expose a basic API from the web assembly module that javascript can call
 */
public class App {

    public static void main(String[] args) {
        for(String arg : args) {
            System.out.println(arg);
        }
        PrefixTreeBuilder builder = new PrefixTreeBuilder();
        Trie trie = builder.build();

        System.out.println("\nSize of Trie: " + String.valueOf(trie.size()));

        String prefix = "cashew";
        System.out.println("\nWords starting with " + prefix + ": ");
        List<String> prefixWords = trie.findWordsWithPrefix(prefix);
        App.printList(prefixWords);
    }

    private static void printList(List<String> list) {
        for(String word : list) {
            System.out.println(word);
        }
    }

}
